# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YmZhODI2Y2UyZTgzMWZhZTQ2MWUyMDdjZDYyYTBlZTEyMjExZWJjMDNkZWQ1NjQ3MjIxOTlkMzdhNzMyNWEzNWVmNWU5YjZlOWY2OGNiYzU3OTU0ZGZhYWQwZmQ2MThkZWIxZTcxNDZhNmYzMTdjZjcyOTEwMjk1NDY3ZWU2ZjI=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
