#common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: OWQ4M2JiNTRlMjk1YWZmYmU5OWY2NTc1M2EwYmVlMTMzZDYwYjlhY2FjZGNiNzI1NWRmMGE2M2E0MzhiZDRkYTZhYTMzNWNkZjZjYmI2MGYyMTQzNTg0MTQ1OWQ1ODEwZjFmMw==
management:
  metrics:
    export:
      prometheus:
        enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
